# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

import subprocess

class Ui_MainWindow(object):

    def back(self):
        self.close

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(550, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.bchamp = QtWidgets.QPushButton(self.centralwidget)
        self.bchamp.setGeometry(QtCore.QRect(330, 300, 75, 23))
        self.bchamp.setObjectName("bchamp")

        self.lineeditplavaetmiha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditplavaetmiha.setGeometry(QtCore.QRect(430, 150, 113, 20))
        self.lineeditplavaetmiha.setObjectName("lineeditplavaetmiha")

        self.lineeditvelikmiha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditvelikmiha.setGeometry(QtCore.QRect(430, 190, 113, 20))
        self.lineeditvelikmiha.setObjectName("lineeditvelikmiha")

        self.lineeditbegmiha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditbegmiha.setGeometry(QtCore.QRect(430, 230, 113, 20))
        self.lineeditbegmiha.setObjectName("lineeditbegmiha")

        self.lineeditbegegor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditbegegor.setGeometry(QtCore.QRect(310, 230, 113, 20))
        self.lineeditbegegor.setObjectName("lineeditbegegor")

        self.lineeditvelikegor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditvelikegor.setGeometry(QtCore.QRect(310, 190, 113, 20))
        self.lineeditvelikegor.setObjectName("lineeditvelikegor")

        self.lineeditplavaetegor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditplavaetegor.setGeometry(QtCore.QRect(310, 150, 113, 20))
        self.lineeditplavaetegor.setObjectName("lineeditplavaetegor")

        self.lineeditplavaetandrey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditplavaetandrey.setGeometry(QtCore.QRect(190, 150, 113, 20))
        self.lineeditplavaetandrey.setObjectName("lineeditplavaetandrey")

        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(740, 10, 50, 30))  
        self.btn_back.setObjectName("btnback")
        self.btn_back.clicked.connect(self.back)
        self.btn_back.setText("Назад")

        self.lineeditvelikandrey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditvelikandrey.setGeometry(QtCore.QRect(190, 190, 113, 20))
        self.lineeditvelikandrey.setObjectName("lineeditvelikandrey")

        self.lineeditbegandrey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditbegandrey.setGeometry(QtCore.QRect(190, 230, 113, 20))
        self.lineeditbegandrey.setObjectName("lineeditbegandrey")

        self.linechamp = QtWidgets.QLineEdit(self.centralwidget)
        self.linechamp.setGeometry(QtCore.QRect(310, 330, 113, 20))
        self.linechamp.setObjectName("linechamp")

        self.labelandrey = QtWidgets.QLabel(self.centralwidget)
        self.labelandrey.setGeometry(QtCore.QRect(220, 120, 47, 13))
        self.labelandrey.setObjectName("labelandrey")

        self.labelegor = QtWidgets.QLabel(self.centralwidget)
        self.labelegor.setGeometry(QtCore.QRect(350, 120, 47, 13))
        self.labelegor.setObjectName("labelegor")

        self.labelmiha = QtWidgets.QLabel(self.centralwidget)
        self.labelmiha.setGeometry(QtCore.QRect(460, 120, 47, 13))
        self.labelmiha.setObjectName("labelmiha")

        self.labelspeed = QtWidgets.QLabel(self.centralwidget)
        self.labelspeed.setGeometry(QtCore.QRect(130, 120, 47, 13))
        self.labelspeed.setObjectName("labelspeed")

        self.labelplavaet = QtWidgets.QLabel(self.centralwidget)
        self.labelplavaet.setGeometry(QtCore.QRect(96, 150, 81, 20))
        self.labelplavaet.setObjectName("labelplavaet")

        self.labelvelik = QtWidgets.QLabel(self.centralwidget)
        self.labelvelik.setGeometry(QtCore.QRect(96, 190, 81, 20))
        self.labelvelik.setObjectName("labelvelik")

        self.labelbeg = QtWidgets.QLabel(self.centralwidget)
        self.labelbeg.setGeometry(QtCore.QRect(126, 230, 51, 20))
        self.labelbeg.setObjectName("labelbeg")

        self.labelmain = QtWidgets.QLabel(self.centralwidget)
        self.labelmain.setGeometry(QtCore.QRect(290, 80, 151, 16))
        self.labelmain.setObjectName("labelmain")

        self.lineeditspeedandrey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditspeedandrey.setGeometry(QtCore.QRect(190, 260, 113, 20))
        self.lineeditspeedandrey.setObjectName("lineeditspeedandrey")

        self.lineeditspeedegor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditspeedegor.setGeometry(QtCore.QRect(310, 260, 113, 20))
        self.lineeditspeedegor.setObjectName("lineeditspeedegor")

        self.lineeditspeedmiha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineeditspeedmiha.setGeometry(QtCore.QRect(430, 260, 113, 20))
        self.lineeditspeedmiha.setObjectName("lineeditspeedmiha")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.calculate_speed)
        self.bchamp.clicked.connect(self.find_champion)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Скорость"))
        self.bchamp.setText(_translate("MainWindow", "Чемпион"))
        self.labelandrey.setText(_translate("MainWindow", "Андрей"))
        self.labelegor.setText(_translate("MainWindow", "Егор"))
        self.labelmiha.setText(_translate("MainWindow", "Михаил"))
        self.labelspeed.setText(_translate("MainWindow", "Скорость"))
        self.labelplavaet.setText(_translate("MainWindow", "Плавает м.мин"))
        self.labelvelik.setText(_translate("MainWindow", "Велосипед км ч"))
        self.labelbeg.setText(_translate("MainWindow", "Бег км ч"))
        self.labelmain.setText(_translate("MainWindow", "Соревнования по триатлону"))

    def calculate_speed(self):
            plavaet_andrey = float(self.lineeditplavaetandrey.text())
            velik_andrey = float(self.lineeditvelikandrey.text())
            beg_andrey = float(self.lineeditbegandrey.text())
            
            plavaet_egor = float(self.lineeditplavaetegor.text())
            velik_egor = float(self.lineeditvelikegor.text())
            beg_egor = float(self.lineeditbegegor.text())
            
            plavaet_miha = float(self.lineeditplavaetmiha.text())
            velik_miha = float(self.lineeditvelikmiha.text())
            beg_miha = float(self.lineeditbegmiha.text())

            speed_andrey = (plavaet_andrey + velik_andrey + beg_andrey) / 3
            speed_egor = (plavaet_egor + velik_egor + beg_egor) / 3
            speed_miha = (plavaet_miha + velik_miha + beg_miha) / 3

            self.lineeditspeedandrey.setText(f"{speed_andrey:.2f}")
            self.lineeditspeedegor.setText(f"{speed_egor:.2f}")
            self.lineeditspeedmiha.setText(f"{speed_miha:.2f}")

    def find_champion(self):
        speed_andrey = float(self.lineeditspeedandrey.text())
        speed_egor = float(self.lineeditspeedegor.text())
        speed_miha = float(self.lineeditspeedmiha.text())

        if speed_andrey >= max(speed_andrey, speed_egor, speed_miha):
            self.linechamp.setText("Андрей")
        elif speed_egor >= max(speed_andrey, speed_egor, speed_miha):
            self.linechamp.setText("Егор")
        else:
            self.linechamp.setText("Михаил")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
